name: flutterexploration
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  build: ^1.1.6

  # This package contains a set of high-level functions and classes that make 
  # it easy to consume HTTP resources. It's multi-platform, and supports mobile, 
  # desktop, and the browser.
  http: ^0.13.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # A package containing the most ~5000 used English words and some utility 
  # functions.
  english_words: ^3.1.5

  # The web_socket_channel package provides StreamChannel wrappers for WebSocket 
  # connections. 
  web_socket_channel: ^1.1.0

  # SQLite plugin
  sqflite: ^1.3.1

  # A Flutter plugin for finding commonly used locations on the filesystem. Supports 
  # iOS, Android, Linux and MacOS. Not all methods are supported on all platforms.
  path_provider: 2.0.0

  # Wraps platform-specific persistent storage for simple data (NSUserDefaults on iOS 
  # and macOS, SharedPreferences on Android, etc.). Data may be persisted to disk asynchronously, 
  # and there is no guarantee that writes will be persisted to disk after returning, so this 
  # plugin must not be used for storing critical data.
  shared_preferences: 2.0.4

  # Provides APIs for debugging and error logging.
  logging: 1.0.0

  # A package to include fonts from fonts.google.com in your Flutter app.
  google_fonts: 2.0.0

  # Syntax highlighting widget for Flutter with lots of languages and themes support.
  flutter_highlight: 0.6.0

  # A minimalistic Flutter game engine.
  flame: ^1.0.0-rc9

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_config: ^0.4.1+1
  build_runner: ^1.6.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/loading.gif
    - assets/fonts/
    - assets/images/examples/animation/chopper.png
    - assets/images/examples/animation/chopper.json
    - assets/images/examples/animation/creature.png
    - assets/images/examples/collision/whizzie-fly.png
    - assets/images/examples/collision/whizzie-smash.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
